name: Back-end build and deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build with Maven
        working-directory: Restaurant_ordering_System_Backend
        run: |
          mvn clean package
          echo "begin copy ruoyi-admin "
          cp ./ruoyi-admin/target/ruoyi-admin.jar ../docker/ruoyi-admin/jar

      # - name: Build Maven Test
      #   run: |
      #     mvn test

      - name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build Redis-1 and Push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/redis
          push: true
          tags: ${{ secrets.USERNAME }}/redis-1:v1
      
      - name: Build backend and Push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/ruoyi-admin
          push: true
          tags: ${{ secrets.USERNAME }}/backend:v1

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$EC2_BACKEND" >> ~/.ssh/known_hosts
          ssh-keyscan -H "$EC2_REDIS" >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_BACKEND: ${{ secrets.EC2_BACKEND }}
          EC2_REDIS: ${{ secrets.EC2_REDIS }}

      # docker run --name ruoyi-redis -p 6379:6379 -d linfan1130/redis-1:v1
      - name: Deploy Redis-1 to Cloud
        working-directory: docker/redis
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@$EC2_HOST "docker pull $USERNAME/redis-1:v1"
        env:
          EC2_HOST: ${{ secrets.EC2_REDIS }}
          USERNAME: ${{ secrets.USERNAME }}

      # docker run --network="host" --name backend -p 8080:8080 -d linfan1130/backend:v1
      - name: Deploy backend to Cloud
        working-directory: docker/ruoyi-admin
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@$EC2_HOST "docker pull $USERNAME/backend:v1"
        env:
          EC2_HOST: ${{ secrets.EC2_BACKEND }}
          USERNAME: ${{ secrets.USERNAME }}